/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthenticatedAdditionalAssignmentsRouteImport } from './routes/_authenticated/additional-assignments'
import { Route as AuthenticatedAnalyticsRouteImport } from './routes/_authenticated/analytics'
import { Route as AuthenticatedAppealsRouteImport } from './routes/_authenticated/appeals'
import { Route as AuthenticatedAppealsCommitteeRouteImport } from './routes/_authenticated/appeals-committee'
import { Route as AuthenticatedAppraisalRouteImport } from './routes/_authenticated/appraisal'
import { Route as AuthenticatedCecRouteImport } from './routes/_authenticated/cec'
import { Route as AuthenticatedChangePasswordRouteImport } from './routes/_authenticated/change-password'
import { Route as AuthenticatedChiefOfficerRouteImport } from './routes/_authenticated/chief-officer'
import { Route as AuthenticatedContinuousReviewRouteImport } from './routes/_authenticated/continuous-review'
import { Route as AuthenticatedContractsRouteImport } from './routes/_authenticated/contracts'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedDepartmentAdminRouteImport } from './routes/_authenticated/department-admin'
import { Route as AuthenticatedDeptAdminRouteImport } from './routes/_authenticated/dept-admin'
import { Route as AuthenticatedDirectorRouteImport } from './routes/_authenticated/director'
import { Route as AuthenticatedEndyearRouteImport } from './routes/_authenticated/endyear'
import { Route as AuthenticatedGovernorRouteImport } from './routes/_authenticated/governor'
import { Route as AuthenticatedMidyearRouteImport } from './routes/_authenticated/midyear'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedQuarterlyRouteImport } from './routes/_authenticated/quarterly'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated/reports'
import { Route as AuthenticatedSearchRouteImport } from './routes/_authenticated/search'
import { Route as AuthenticatedSignOffRouteImport } from './routes/_authenticated/sign-off'
import { Route as AuthenticatedSpasReportsRouteImport } from './routes/_authenticated/spas-reports'
import { Route as AuthenticatedSuperAdminRouteImport } from './routes/_authenticated/super-admin'
import { Route as AuthenticatedSupervisorRouteImport } from './routes/_authenticated/supervisor'
import { Route as AuthenticatedWorkplansRouteImport } from './routes/_authenticated/workplans'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedAdminAuditRouteImport } from './routes/_authenticated/admin.audit'
import { Route as AuthenticatedAdminContractsRouteImport } from './routes/_authenticated/admin.contracts'
import { Route as AuthenticatedAdminCyclesRouteImport } from './routes/_authenticated/admin.cycles'
import { Route as AuthenticatedAdminElevateRouteImport } from './routes/_authenticated/admin.elevate'
import { Route as AuthenticatedAdminImportRouteImport } from './routes/_authenticated/admin.import'
import { Route as AuthenticatedAdminLoginAuditRouteImport } from './routes/_authenticated/admin.login-audit'
import { Route as AuthenticatedAdminMatrixRouteImport } from './routes/_authenticated/admin.matrix'
import { Route as AuthenticatedAdminOrgStructureRouteImport } from './routes/_authenticated/admin.org-structure'
import { Route as AuthenticatedAdminRolesRouteImport } from './routes/_authenticated/admin.roles'
import { Route as AuthenticatedAdminStatusRouteImport } from './routes/_authenticated/admin.status'
import { Route as AuthenticatedAdminSyncRouteImport } from './routes/_authenticated/admin.sync'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin.users'
import { Route as AuthenticatedCommitteeAppealsRouteImport } from './routes/_authenticated/committee.appeals'
import { Route as AuthenticatedSupervisorInboxRouteImport } from './routes/_authenticated/supervisor.inbox'
import { Route as ApiPublicBootstrapSuper26RouteImport } from './routes/api/public/bootstrap-super26'
import { Route as ApiPublicPayrollSyncRouteImport } from './routes/api/public/payroll-sync'
import { Route as AuthenticatedSupervisorReviewIdRouteImport } from './routes/_authenticated/supervisor.review.$id'
import { Route as ApiPublicHooksAppraisalRemindersRouteImport } from './routes/api/public/hooks/appraisal-reminders'
import { Route as ApiPublicHooksContractMonitorRouteImport } from './routes/api/public/hooks/contract-monitor'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdditionalAssignmentsRoute =
  AuthenticatedAdditionalAssignmentsRouteImport.update({
    id: '/additional-assignments',
    path: '/additional-assignments',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAnalyticsRoute = AuthenticatedAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppealsRoute = AuthenticatedAppealsRouteImport.update({
  id: '/appeals',
  path: '/appeals',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppealsCommitteeRoute =
  AuthenticatedAppealsCommitteeRouteImport.update({
    id: '/appeals-committee',
    path: '/appeals-committee',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppraisalRoute = AuthenticatedAppraisalRouteImport.update({
  id: '/appraisal',
  path: '/appraisal',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCecRoute = AuthenticatedCecRouteImport.update({
  id: '/cec',
  path: '/cec',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedChangePasswordRoute =
  AuthenticatedChangePasswordRouteImport.update({
    id: '/change-password',
    path: '/change-password',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedChiefOfficerRoute =
  AuthenticatedChiefOfficerRouteImport.update({
    id: '/chief-officer',
    path: '/chief-officer',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedContinuousReviewRoute =
  AuthenticatedContinuousReviewRouteImport.update({
    id: '/continuous-review',
    path: '/continuous-review',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedContractsRoute = AuthenticatedContractsRouteImport.update({
  id: '/contracts',
  path: '/contracts',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDepartmentAdminRoute =
  AuthenticatedDepartmentAdminRouteImport.update({
    id: '/department-admin',
    path: '/department-admin',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDeptAdminRoute = AuthenticatedDeptAdminRouteImport.update({
  id: '/dept-admin',
  path: '/dept-admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDirectorRoute = AuthenticatedDirectorRouteImport.update({
  id: '/director',
  path: '/director',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEndyearRoute = AuthenticatedEndyearRouteImport.update({
  id: '/endyear',
  path: '/endyear',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGovernorRoute = AuthenticatedGovernorRouteImport.update({
  id: '/governor',
  path: '/governor',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMidyearRoute = AuthenticatedMidyearRouteImport.update({
  id: '/midyear',
  path: '/midyear',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedQuarterlyRoute = AuthenticatedQuarterlyRouteImport.update({
  id: '/quarterly',
  path: '/quarterly',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSearchRoute = AuthenticatedSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSignOffRoute = AuthenticatedSignOffRouteImport.update({
  id: '/sign-off',
  path: '/sign-off',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSpasReportsRoute =
  AuthenticatedSpasReportsRouteImport.update({
    id: '/spas-reports',
    path: '/spas-reports',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSuperAdminRoute = AuthenticatedSuperAdminRouteImport.update({
  id: '/super-admin',
  path: '/super-admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSupervisorRoute = AuthenticatedSupervisorRouteImport.update({
  id: '/supervisor',
  path: '/supervisor',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedWorkplansRoute = AuthenticatedWorkplansRouteImport.update({
  id: '/workplans',
  path: '/workplans',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminAuditRoute = AuthenticatedAdminAuditRouteImport.update({
  id: '/admin/audit',
  path: '/admin/audit',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminContractsRoute =
  AuthenticatedAdminContractsRouteImport.update({
    id: '/admin/contracts',
    path: '/admin/contracts',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminCyclesRoute =
  AuthenticatedAdminCyclesRouteImport.update({
    id: '/admin/cycles',
    path: '/admin/cycles',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminElevateRoute =
  AuthenticatedAdminElevateRouteImport.update({
    id: '/admin/elevate',
    path: '/admin/elevate',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminImportRoute =
  AuthenticatedAdminImportRouteImport.update({
    id: '/admin/import',
    path: '/admin/import',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminLoginAuditRoute =
  AuthenticatedAdminLoginAuditRouteImport.update({
    id: '/admin/login-audit',
    path: '/admin/login-audit',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminMatrixRoute =
  AuthenticatedAdminMatrixRouteImport.update({
    id: '/admin/matrix',
    path: '/admin/matrix',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminOrgStructureRoute =
  AuthenticatedAdminOrgStructureRouteImport.update({
    id: '/admin/org-structure',
    path: '/admin/org-structure',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminRolesRoute = AuthenticatedAdminRolesRouteImport.update({
  id: '/admin/roles',
  path: '/admin/roles',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminStatusRoute =
  AuthenticatedAdminStatusRouteImport.update({
    id: '/admin/status',
    path: '/admin/status',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminSyncRoute = AuthenticatedAdminSyncRouteImport.update({
  id: '/admin/sync',
  path: '/admin/sync',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCommitteeAppealsRoute =
  AuthenticatedCommitteeAppealsRouteImport.update({
    id: '/committee/appeals',
    path: '/committee/appeals',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSupervisorInboxRoute =
  AuthenticatedSupervisorInboxRouteImport.update({
    id: '/inbox',
    path: '/inbox',
    getParentRoute: () => AuthenticatedSupervisorRoute,
  } as any)
const ApiPublicBootstrapSuper26Route =
  ApiPublicBootstrapSuper26RouteImport.update({
    id: '/api/public/bootstrap-super26',
    path: '/api/public/bootstrap-super26',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicPayrollSyncRoute = ApiPublicPayrollSyncRouteImport.update({
  id: '/api/public/payroll-sync',
  path: '/api/public/payroll-sync',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSupervisorReviewIdRoute =
  AuthenticatedSupervisorReviewIdRouteImport.update({
    id: '/review/$id',
    path: '/review/$id',
    getParentRoute: () => AuthenticatedSupervisorRoute,
  } as any)
const ApiPublicHooksAppraisalRemindersRoute =
  ApiPublicHooksAppraisalRemindersRouteImport.update({
    id: '/api/public/hooks/appraisal-reminders',
    path: '/api/public/hooks/appraisal-reminders',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksContractMonitorRoute =
  ApiPublicHooksContractMonitorRouteImport.update({
    id: '/api/public/hooks/contract-monitor',
    path: '/api/public/hooks/contract-monitor',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/additional-assignments': typeof AuthenticatedAdditionalAssignmentsRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/appeals': typeof AuthenticatedAppealsRoute
  '/appeals-committee': typeof AuthenticatedAppealsCommitteeRoute
  '/appraisal': typeof AuthenticatedAppraisalRoute
  '/cec': typeof AuthenticatedCecRoute
  '/change-password': typeof AuthenticatedChangePasswordRoute
  '/chief-officer': typeof AuthenticatedChiefOfficerRoute
  '/continuous-review': typeof AuthenticatedContinuousReviewRoute
  '/contracts': typeof AuthenticatedContractsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/department-admin': typeof AuthenticatedDepartmentAdminRoute
  '/dept-admin': typeof AuthenticatedDeptAdminRoute
  '/director': typeof AuthenticatedDirectorRoute
  '/endyear': typeof AuthenticatedEndyearRoute
  '/governor': typeof AuthenticatedGovernorRoute
  '/midyear': typeof AuthenticatedMidyearRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/quarterly': typeof AuthenticatedQuarterlyRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/search': typeof AuthenticatedSearchRoute
  '/sign-off': typeof AuthenticatedSignOffRoute
  '/spas-reports': typeof AuthenticatedSpasReportsRoute
  '/super-admin': typeof AuthenticatedSuperAdminRoute
  '/supervisor': typeof AuthenticatedSupervisorRouteWithChildren
  '/workplans': typeof AuthenticatedWorkplansRoute
  '/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/admin/contracts': typeof AuthenticatedAdminContractsRoute
  '/admin/cycles': typeof AuthenticatedAdminCyclesRoute
  '/admin/elevate': typeof AuthenticatedAdminElevateRoute
  '/admin/import': typeof AuthenticatedAdminImportRoute
  '/admin/login-audit': typeof AuthenticatedAdminLoginAuditRoute
  '/admin/matrix': typeof AuthenticatedAdminMatrixRoute
  '/admin/org-structure': typeof AuthenticatedAdminOrgStructureRoute
  '/admin/roles': typeof AuthenticatedAdminRolesRoute
  '/admin/status': typeof AuthenticatedAdminStatusRoute
  '/admin/sync': typeof AuthenticatedAdminSyncRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/committee/appeals': typeof AuthenticatedCommitteeAppealsRoute
  '/supervisor/inbox': typeof AuthenticatedSupervisorInboxRoute
  '/api/public/bootstrap-super26': typeof ApiPublicBootstrapSuper26Route
  '/api/public/payroll-sync': typeof ApiPublicPayrollSyncRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/supervisor/review/$id': typeof AuthenticatedSupervisorReviewIdRoute
  '/api/public/hooks/appraisal-reminders': typeof ApiPublicHooksAppraisalRemindersRoute
  '/api/public/hooks/contract-monitor': typeof ApiPublicHooksContractMonitorRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/additional-assignments': typeof AuthenticatedAdditionalAssignmentsRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/appeals': typeof AuthenticatedAppealsRoute
  '/appeals-committee': typeof AuthenticatedAppealsCommitteeRoute
  '/appraisal': typeof AuthenticatedAppraisalRoute
  '/cec': typeof AuthenticatedCecRoute
  '/change-password': typeof AuthenticatedChangePasswordRoute
  '/chief-officer': typeof AuthenticatedChiefOfficerRoute
  '/continuous-review': typeof AuthenticatedContinuousReviewRoute
  '/contracts': typeof AuthenticatedContractsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/department-admin': typeof AuthenticatedDepartmentAdminRoute
  '/dept-admin': typeof AuthenticatedDeptAdminRoute
  '/director': typeof AuthenticatedDirectorRoute
  '/endyear': typeof AuthenticatedEndyearRoute
  '/governor': typeof AuthenticatedGovernorRoute
  '/midyear': typeof AuthenticatedMidyearRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/quarterly': typeof AuthenticatedQuarterlyRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/search': typeof AuthenticatedSearchRoute
  '/sign-off': typeof AuthenticatedSignOffRoute
  '/spas-reports': typeof AuthenticatedSpasReportsRoute
  '/super-admin': typeof AuthenticatedSuperAdminRoute
  '/supervisor': typeof AuthenticatedSupervisorRouteWithChildren
  '/workplans': typeof AuthenticatedWorkplansRoute
  '/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/admin/contracts': typeof AuthenticatedAdminContractsRoute
  '/admin/cycles': typeof AuthenticatedAdminCyclesRoute
  '/admin/elevate': typeof AuthenticatedAdminElevateRoute
  '/admin/import': typeof AuthenticatedAdminImportRoute
  '/admin/login-audit': typeof AuthenticatedAdminLoginAuditRoute
  '/admin/matrix': typeof AuthenticatedAdminMatrixRoute
  '/admin/org-structure': typeof AuthenticatedAdminOrgStructureRoute
  '/admin/roles': typeof AuthenticatedAdminRolesRoute
  '/admin/status': typeof AuthenticatedAdminStatusRoute
  '/admin/sync': typeof AuthenticatedAdminSyncRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/committee/appeals': typeof AuthenticatedCommitteeAppealsRoute
  '/supervisor/inbox': typeof AuthenticatedSupervisorInboxRoute
  '/api/public/bootstrap-super26': typeof ApiPublicBootstrapSuper26Route
  '/api/public/payroll-sync': typeof ApiPublicPayrollSyncRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/supervisor/review/$id': typeof AuthenticatedSupervisorReviewIdRoute
  '/api/public/hooks/appraisal-reminders': typeof ApiPublicHooksAppraisalRemindersRoute
  '/api/public/hooks/contract-monitor': typeof ApiPublicHooksContractMonitorRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/additional-assignments': typeof AuthenticatedAdditionalAssignmentsRoute
  '/_authenticated/analytics': typeof AuthenticatedAnalyticsRoute
  '/_authenticated/appeals': typeof AuthenticatedAppealsRoute
  '/_authenticated/appeals-committee': typeof AuthenticatedAppealsCommitteeRoute
  '/_authenticated/appraisal': typeof AuthenticatedAppraisalRoute
  '/_authenticated/cec': typeof AuthenticatedCecRoute
  '/_authenticated/change-password': typeof AuthenticatedChangePasswordRoute
  '/_authenticated/chief-officer': typeof AuthenticatedChiefOfficerRoute
  '/_authenticated/continuous-review': typeof AuthenticatedContinuousReviewRoute
  '/_authenticated/contracts': typeof AuthenticatedContractsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/department-admin': typeof AuthenticatedDepartmentAdminRoute
  '/_authenticated/dept-admin': typeof AuthenticatedDeptAdminRoute
  '/_authenticated/director': typeof AuthenticatedDirectorRoute
  '/_authenticated/endyear': typeof AuthenticatedEndyearRoute
  '/_authenticated/governor': typeof AuthenticatedGovernorRoute
  '/_authenticated/midyear': typeof AuthenticatedMidyearRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/quarterly': typeof AuthenticatedQuarterlyRoute
  '/_authenticated/reports': typeof AuthenticatedReportsRoute
  '/_authenticated/search': typeof AuthenticatedSearchRoute
  '/_authenticated/sign-off': typeof AuthenticatedSignOffRoute
  '/_authenticated/spas-reports': typeof AuthenticatedSpasReportsRoute
  '/_authenticated/super-admin': typeof AuthenticatedSuperAdminRoute
  '/_authenticated/supervisor': typeof AuthenticatedSupervisorRouteWithChildren
  '/_authenticated/workplans': typeof AuthenticatedWorkplansRoute
  '/_authenticated/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/_authenticated/admin/contracts': typeof AuthenticatedAdminContractsRoute
  '/_authenticated/admin/cycles': typeof AuthenticatedAdminCyclesRoute
  '/_authenticated/admin/elevate': typeof AuthenticatedAdminElevateRoute
  '/_authenticated/admin/import': typeof AuthenticatedAdminImportRoute
  '/_authenticated/admin/login-audit': typeof AuthenticatedAdminLoginAuditRoute
  '/_authenticated/admin/matrix': typeof AuthenticatedAdminMatrixRoute
  '/_authenticated/admin/org-structure': typeof AuthenticatedAdminOrgStructureRoute
  '/_authenticated/admin/roles': typeof AuthenticatedAdminRolesRoute
  '/_authenticated/admin/status': typeof AuthenticatedAdminStatusRoute
  '/_authenticated/admin/sync': typeof AuthenticatedAdminSyncRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/committee/appeals': typeof AuthenticatedCommitteeAppealsRoute
  '/_authenticated/supervisor/inbox': typeof AuthenticatedSupervisorInboxRoute
  '/api/public/bootstrap-super26': typeof ApiPublicBootstrapSuper26Route
  '/api/public/payroll-sync': typeof ApiPublicPayrollSyncRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/supervisor/review/$id': typeof AuthenticatedSupervisorReviewIdRoute
  '/api/public/hooks/appraisal-reminders': typeof ApiPublicHooksAppraisalRemindersRoute
  '/api/public/hooks/contract-monitor': typeof ApiPublicHooksContractMonitorRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/additional-assignments'
    | '/analytics'
    | '/appeals'
    | '/appeals-committee'
    | '/appraisal'
    | '/cec'
    | '/change-password'
    | '/chief-officer'
    | '/continuous-review'
    | '/contracts'
    | '/dashboard'
    | '/department-admin'
    | '/dept-admin'
    | '/director'
    | '/endyear'
    | '/governor'
    | '/midyear'
    | '/profile'
    | '/quarterly'
    | '/reports'
    | '/search'
    | '/sign-off'
    | '/spas-reports'
    | '/super-admin'
    | '/supervisor'
    | '/workplans'
    | '/admin/audit'
    | '/admin/contracts'
    | '/admin/cycles'
    | '/admin/elevate'
    | '/admin/import'
    | '/admin/login-audit'
    | '/admin/matrix'
    | '/admin/org-structure'
    | '/admin/roles'
    | '/admin/status'
    | '/admin/sync'
    | '/admin/users'
    | '/committee/appeals'
    | '/supervisor/inbox'
    | '/api/public/bootstrap-super26'
    | '/api/public/payroll-sync'
    | '/admin/'
    | '/supervisor/review/$id'
    | '/api/public/hooks/appraisal-reminders'
    | '/api/public/hooks/contract-monitor'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/additional-assignments'
    | '/analytics'
    | '/appeals'
    | '/appeals-committee'
    | '/appraisal'
    | '/cec'
    | '/change-password'
    | '/chief-officer'
    | '/continuous-review'
    | '/contracts'
    | '/dashboard'
    | '/department-admin'
    | '/dept-admin'
    | '/director'
    | '/endyear'
    | '/governor'
    | '/midyear'
    | '/profile'
    | '/quarterly'
    | '/reports'
    | '/search'
    | '/sign-off'
    | '/spas-reports'
    | '/super-admin'
    | '/supervisor'
    | '/workplans'
    | '/admin/audit'
    | '/admin/contracts'
    | '/admin/cycles'
    | '/admin/elevate'
    | '/admin/import'
    | '/admin/login-audit'
    | '/admin/matrix'
    | '/admin/org-structure'
    | '/admin/roles'
    | '/admin/status'
    | '/admin/sync'
    | '/admin/users'
    | '/committee/appeals'
    | '/supervisor/inbox'
    | '/api/public/bootstrap-super26'
    | '/api/public/payroll-sync'
    | '/admin'
    | '/supervisor/review/$id'
    | '/api/public/hooks/appraisal-reminders'
    | '/api/public/hooks/contract-monitor'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/reset-password'
    | '/_authenticated/additional-assignments'
    | '/_authenticated/analytics'
    | '/_authenticated/appeals'
    | '/_authenticated/appeals-committee'
    | '/_authenticated/appraisal'
    | '/_authenticated/cec'
    | '/_authenticated/change-password'
    | '/_authenticated/chief-officer'
    | '/_authenticated/continuous-review'
    | '/_authenticated/contracts'
    | '/_authenticated/dashboard'
    | '/_authenticated/department-admin'
    | '/_authenticated/dept-admin'
    | '/_authenticated/director'
    | '/_authenticated/endyear'
    | '/_authenticated/governor'
    | '/_authenticated/midyear'
    | '/_authenticated/profile'
    | '/_authenticated/quarterly'
    | '/_authenticated/reports'
    | '/_authenticated/search'
    | '/_authenticated/sign-off'
    | '/_authenticated/spas-reports'
    | '/_authenticated/super-admin'
    | '/_authenticated/supervisor'
    | '/_authenticated/workplans'
    | '/_authenticated/admin/audit'
    | '/_authenticated/admin/contracts'
    | '/_authenticated/admin/cycles'
    | '/_authenticated/admin/elevate'
    | '/_authenticated/admin/import'
    | '/_authenticated/admin/login-audit'
    | '/_authenticated/admin/matrix'
    | '/_authenticated/admin/org-structure'
    | '/_authenticated/admin/roles'
    | '/_authenticated/admin/status'
    | '/_authenticated/admin/sync'
    | '/_authenticated/admin/users'
    | '/_authenticated/committee/appeals'
    | '/_authenticated/supervisor/inbox'
    | '/api/public/bootstrap-super26'
    | '/api/public/payroll-sync'
    | '/_authenticated/admin/'
    | '/_authenticated/supervisor/review/$id'
    | '/api/public/hooks/appraisal-reminders'
    | '/api/public/hooks/contract-monitor'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ApiPublicBootstrapSuper26Route: typeof ApiPublicBootstrapSuper26Route
  ApiPublicPayrollSyncRoute: typeof ApiPublicPayrollSyncRoute
  ApiPublicHooksAppraisalRemindersRoute: typeof ApiPublicHooksAppraisalRemindersRoute
  ApiPublicHooksContractMonitorRoute: typeof ApiPublicHooksContractMonitorRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/additional-assignments': {
      id: '/_authenticated/additional-assignments'
      path: '/additional-assignments'
      fullPath: '/additional-assignments'
      preLoaderRoute: typeof AuthenticatedAdditionalAssignmentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/analytics': {
      id: '/_authenticated/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AuthenticatedAnalyticsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/appeals': {
      id: '/_authenticated/appeals'
      path: '/appeals'
      fullPath: '/appeals'
      preLoaderRoute: typeof AuthenticatedAppealsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/appeals-committee': {
      id: '/_authenticated/appeals-committee'
      path: '/appeals-committee'
      fullPath: '/appeals-committee'
      preLoaderRoute: typeof AuthenticatedAppealsCommitteeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/appraisal': {
      id: '/_authenticated/appraisal'
      path: '/appraisal'
      fullPath: '/appraisal'
      preLoaderRoute: typeof AuthenticatedAppraisalRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cec': {
      id: '/_authenticated/cec'
      path: '/cec'
      fullPath: '/cec'
      preLoaderRoute: typeof AuthenticatedCecRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/change-password': {
      id: '/_authenticated/change-password'
      path: '/change-password'
      fullPath: '/change-password'
      preLoaderRoute: typeof AuthenticatedChangePasswordRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/chief-officer': {
      id: '/_authenticated/chief-officer'
      path: '/chief-officer'
      fullPath: '/chief-officer'
      preLoaderRoute: typeof AuthenticatedChiefOfficerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/continuous-review': {
      id: '/_authenticated/continuous-review'
      path: '/continuous-review'
      fullPath: '/continuous-review'
      preLoaderRoute: typeof AuthenticatedContinuousReviewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/contracts': {
      id: '/_authenticated/contracts'
      path: '/contracts'
      fullPath: '/contracts'
      preLoaderRoute: typeof AuthenticatedContractsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/department-admin': {
      id: '/_authenticated/department-admin'
      path: '/department-admin'
      fullPath: '/department-admin'
      preLoaderRoute: typeof AuthenticatedDepartmentAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dept-admin': {
      id: '/_authenticated/dept-admin'
      path: '/dept-admin'
      fullPath: '/dept-admin'
      preLoaderRoute: typeof AuthenticatedDeptAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/director': {
      id: '/_authenticated/director'
      path: '/director'
      fullPath: '/director'
      preLoaderRoute: typeof AuthenticatedDirectorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/endyear': {
      id: '/_authenticated/endyear'
      path: '/endyear'
      fullPath: '/endyear'
      preLoaderRoute: typeof AuthenticatedEndyearRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/governor': {
      id: '/_authenticated/governor'
      path: '/governor'
      fullPath: '/governor'
      preLoaderRoute: typeof AuthenticatedGovernorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/midyear': {
      id: '/_authenticated/midyear'
      path: '/midyear'
      fullPath: '/midyear'
      preLoaderRoute: typeof AuthenticatedMidyearRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/quarterly': {
      id: '/_authenticated/quarterly'
      path: '/quarterly'
      fullPath: '/quarterly'
      preLoaderRoute: typeof AuthenticatedQuarterlyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/search': {
      id: '/_authenticated/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof AuthenticatedSearchRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sign-off': {
      id: '/_authenticated/sign-off'
      path: '/sign-off'
      fullPath: '/sign-off'
      preLoaderRoute: typeof AuthenticatedSignOffRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/spas-reports': {
      id: '/_authenticated/spas-reports'
      path: '/spas-reports'
      fullPath: '/spas-reports'
      preLoaderRoute: typeof AuthenticatedSpasReportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/super-admin': {
      id: '/_authenticated/super-admin'
      path: '/super-admin'
      fullPath: '/super-admin'
      preLoaderRoute: typeof AuthenticatedSuperAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/supervisor': {
      id: '/_authenticated/supervisor'
      path: '/supervisor'
      fullPath: '/supervisor'
      preLoaderRoute: typeof AuthenticatedSupervisorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/workplans': {
      id: '/_authenticated/workplans'
      path: '/workplans'
      fullPath: '/workplans'
      preLoaderRoute: typeof AuthenticatedWorkplansRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/audit': {
      id: '/_authenticated/admin/audit'
      path: '/admin/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AuthenticatedAdminAuditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/contracts': {
      id: '/_authenticated/admin/contracts'
      path: '/admin/contracts'
      fullPath: '/admin/contracts'
      preLoaderRoute: typeof AuthenticatedAdminContractsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/cycles': {
      id: '/_authenticated/admin/cycles'
      path: '/admin/cycles'
      fullPath: '/admin/cycles'
      preLoaderRoute: typeof AuthenticatedAdminCyclesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/elevate': {
      id: '/_authenticated/admin/elevate'
      path: '/admin/elevate'
      fullPath: '/admin/elevate'
      preLoaderRoute: typeof AuthenticatedAdminElevateRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/import': {
      id: '/_authenticated/admin/import'
      path: '/admin/import'
      fullPath: '/admin/import'
      preLoaderRoute: typeof AuthenticatedAdminImportRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/login-audit': {
      id: '/_authenticated/admin/login-audit'
      path: '/admin/login-audit'
      fullPath: '/admin/login-audit'
      preLoaderRoute: typeof AuthenticatedAdminLoginAuditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/matrix': {
      id: '/_authenticated/admin/matrix'
      path: '/admin/matrix'
      fullPath: '/admin/matrix'
      preLoaderRoute: typeof AuthenticatedAdminMatrixRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/org-structure': {
      id: '/_authenticated/admin/org-structure'
      path: '/admin/org-structure'
      fullPath: '/admin/org-structure'
      preLoaderRoute: typeof AuthenticatedAdminOrgStructureRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/roles': {
      id: '/_authenticated/admin/roles'
      path: '/admin/roles'
      fullPath: '/admin/roles'
      preLoaderRoute: typeof AuthenticatedAdminRolesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/status': {
      id: '/_authenticated/admin/status'
      path: '/admin/status'
      fullPath: '/admin/status'
      preLoaderRoute: typeof AuthenticatedAdminStatusRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/sync': {
      id: '/_authenticated/admin/sync'
      path: '/admin/sync'
      fullPath: '/admin/sync'
      preLoaderRoute: typeof AuthenticatedAdminSyncRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/committee/appeals': {
      id: '/_authenticated/committee/appeals'
      path: '/committee/appeals'
      fullPath: '/committee/appeals'
      preLoaderRoute: typeof AuthenticatedCommitteeAppealsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/supervisor/inbox': {
      id: '/_authenticated/supervisor/inbox'
      path: '/inbox'
      fullPath: '/supervisor/inbox'
      preLoaderRoute: typeof AuthenticatedSupervisorInboxRouteImport
      parentRoute: typeof AuthenticatedSupervisorRoute
    }
    '/api/public/bootstrap-super26': {
      id: '/api/public/bootstrap-super26'
      path: '/api/public/bootstrap-super26'
      fullPath: '/api/public/bootstrap-super26'
      preLoaderRoute: typeof ApiPublicBootstrapSuper26RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/payroll-sync': {
      id: '/api/public/payroll-sync'
      path: '/api/public/payroll-sync'
      fullPath: '/api/public/payroll-sync'
      preLoaderRoute: typeof ApiPublicPayrollSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/supervisor/review/$id': {
      id: '/_authenticated/supervisor/review/$id'
      path: '/review/$id'
      fullPath: '/supervisor/review/$id'
      preLoaderRoute: typeof AuthenticatedSupervisorReviewIdRouteImport
      parentRoute: typeof AuthenticatedSupervisorRoute
    }
    '/api/public/hooks/appraisal-reminders': {
      id: '/api/public/hooks/appraisal-reminders'
      path: '/api/public/hooks/appraisal-reminders'
      fullPath: '/api/public/hooks/appraisal-reminders'
      preLoaderRoute: typeof ApiPublicHooksAppraisalRemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/contract-monitor': {
      id: '/api/public/hooks/contract-monitor'
      path: '/api/public/hooks/contract-monitor'
      fullPath: '/api/public/hooks/contract-monitor'
      preLoaderRoute: typeof ApiPublicHooksContractMonitorRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedSupervisorRouteChildren {
  AuthenticatedSupervisorInboxRoute: typeof AuthenticatedSupervisorInboxRoute
  AuthenticatedSupervisorReviewIdRoute: typeof AuthenticatedSupervisorReviewIdRoute
}

const AuthenticatedSupervisorRouteChildren: AuthenticatedSupervisorRouteChildren =
  {
    AuthenticatedSupervisorInboxRoute: AuthenticatedSupervisorInboxRoute,
    AuthenticatedSupervisorReviewIdRoute: AuthenticatedSupervisorReviewIdRoute,
  }

const AuthenticatedSupervisorRouteWithChildren =
  AuthenticatedSupervisorRoute._addFileChildren(
    AuthenticatedSupervisorRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdditionalAssignmentsRoute: typeof AuthenticatedAdditionalAssignmentsRoute
  AuthenticatedAnalyticsRoute: typeof AuthenticatedAnalyticsRoute
  AuthenticatedAppealsRoute: typeof AuthenticatedAppealsRoute
  AuthenticatedAppealsCommitteeRoute: typeof AuthenticatedAppealsCommitteeRoute
  AuthenticatedAppraisalRoute: typeof AuthenticatedAppraisalRoute
  AuthenticatedCecRoute: typeof AuthenticatedCecRoute
  AuthenticatedChangePasswordRoute: typeof AuthenticatedChangePasswordRoute
  AuthenticatedChiefOfficerRoute: typeof AuthenticatedChiefOfficerRoute
  AuthenticatedContinuousReviewRoute: typeof AuthenticatedContinuousReviewRoute
  AuthenticatedContractsRoute: typeof AuthenticatedContractsRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDepartmentAdminRoute: typeof AuthenticatedDepartmentAdminRoute
  AuthenticatedDeptAdminRoute: typeof AuthenticatedDeptAdminRoute
  AuthenticatedDirectorRoute: typeof AuthenticatedDirectorRoute
  AuthenticatedEndyearRoute: typeof AuthenticatedEndyearRoute
  AuthenticatedGovernorRoute: typeof AuthenticatedGovernorRoute
  AuthenticatedMidyearRoute: typeof AuthenticatedMidyearRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedQuarterlyRoute: typeof AuthenticatedQuarterlyRoute
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRoute
  AuthenticatedSearchRoute: typeof AuthenticatedSearchRoute
  AuthenticatedSignOffRoute: typeof AuthenticatedSignOffRoute
  AuthenticatedSpasReportsRoute: typeof AuthenticatedSpasReportsRoute
  AuthenticatedSuperAdminRoute: typeof AuthenticatedSuperAdminRoute
  AuthenticatedSupervisorRoute: typeof AuthenticatedSupervisorRouteWithChildren
  AuthenticatedWorkplansRoute: typeof AuthenticatedWorkplansRoute
  AuthenticatedAdminAuditRoute: typeof AuthenticatedAdminAuditRoute
  AuthenticatedAdminContractsRoute: typeof AuthenticatedAdminContractsRoute
  AuthenticatedAdminCyclesRoute: typeof AuthenticatedAdminCyclesRoute
  AuthenticatedAdminElevateRoute: typeof AuthenticatedAdminElevateRoute
  AuthenticatedAdminImportRoute: typeof AuthenticatedAdminImportRoute
  AuthenticatedAdminLoginAuditRoute: typeof AuthenticatedAdminLoginAuditRoute
  AuthenticatedAdminMatrixRoute: typeof AuthenticatedAdminMatrixRoute
  AuthenticatedAdminOrgStructureRoute: typeof AuthenticatedAdminOrgStructureRoute
  AuthenticatedAdminRolesRoute: typeof AuthenticatedAdminRolesRoute
  AuthenticatedAdminStatusRoute: typeof AuthenticatedAdminStatusRoute
  AuthenticatedAdminSyncRoute: typeof AuthenticatedAdminSyncRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
  AuthenticatedCommitteeAppealsRoute: typeof AuthenticatedCommitteeAppealsRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdditionalAssignmentsRoute:
    AuthenticatedAdditionalAssignmentsRoute,
  AuthenticatedAnalyticsRoute: AuthenticatedAnalyticsRoute,
  AuthenticatedAppealsRoute: AuthenticatedAppealsRoute,
  AuthenticatedAppealsCommitteeRoute: AuthenticatedAppealsCommitteeRoute,
  AuthenticatedAppraisalRoute: AuthenticatedAppraisalRoute,
  AuthenticatedCecRoute: AuthenticatedCecRoute,
  AuthenticatedChangePasswordRoute: AuthenticatedChangePasswordRoute,
  AuthenticatedChiefOfficerRoute: AuthenticatedChiefOfficerRoute,
  AuthenticatedContinuousReviewRoute: AuthenticatedContinuousReviewRoute,
  AuthenticatedContractsRoute: AuthenticatedContractsRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDepartmentAdminRoute: AuthenticatedDepartmentAdminRoute,
  AuthenticatedDeptAdminRoute: AuthenticatedDeptAdminRoute,
  AuthenticatedDirectorRoute: AuthenticatedDirectorRoute,
  AuthenticatedEndyearRoute: AuthenticatedEndyearRoute,
  AuthenticatedGovernorRoute: AuthenticatedGovernorRoute,
  AuthenticatedMidyearRoute: AuthenticatedMidyearRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedQuarterlyRoute: AuthenticatedQuarterlyRoute,
  AuthenticatedReportsRoute: AuthenticatedReportsRoute,
  AuthenticatedSearchRoute: AuthenticatedSearchRoute,
  AuthenticatedSignOffRoute: AuthenticatedSignOffRoute,
  AuthenticatedSpasReportsRoute: AuthenticatedSpasReportsRoute,
  AuthenticatedSuperAdminRoute: AuthenticatedSuperAdminRoute,
  AuthenticatedSupervisorRoute: AuthenticatedSupervisorRouteWithChildren,
  AuthenticatedWorkplansRoute: AuthenticatedWorkplansRoute,
  AuthenticatedAdminAuditRoute: AuthenticatedAdminAuditRoute,
  AuthenticatedAdminContractsRoute: AuthenticatedAdminContractsRoute,
  AuthenticatedAdminCyclesRoute: AuthenticatedAdminCyclesRoute,
  AuthenticatedAdminElevateRoute: AuthenticatedAdminElevateRoute,
  AuthenticatedAdminImportRoute: AuthenticatedAdminImportRoute,
  AuthenticatedAdminLoginAuditRoute: AuthenticatedAdminLoginAuditRoute,
  AuthenticatedAdminMatrixRoute: AuthenticatedAdminMatrixRoute,
  AuthenticatedAdminOrgStructureRoute: AuthenticatedAdminOrgStructureRoute,
  AuthenticatedAdminRolesRoute: AuthenticatedAdminRolesRoute,
  AuthenticatedAdminStatusRoute: AuthenticatedAdminStatusRoute,
  AuthenticatedAdminSyncRoute: AuthenticatedAdminSyncRoute,
  AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
  AuthenticatedCommitteeAppealsRoute: AuthenticatedCommitteeAppealsRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ApiPublicBootstrapSuper26Route: ApiPublicBootstrapSuper26Route,
  ApiPublicPayrollSyncRoute: ApiPublicPayrollSyncRoute,
  ApiPublicHooksAppraisalRemindersRoute: ApiPublicHooksAppraisalRemindersRoute,
  ApiPublicHooksContractMonitorRoute: ApiPublicHooksContractMonitorRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
